export interface CityData {
  label: string;
  districts: string[];
}

export const CITIES: CityData[] = [
  { label: "Adana", districts: ["Seyhan", "Çukurova", "Yüreğir", "Sarıçam", "Ceyhan", "Kozan", "İmamoğlu", "Karaisalı", "Aladağ", "Feke", "Karataş", "Pozantı", "Saimbeyli", "Tufanbeyli", "Yumurtalık"] },
  { label: "Adıyaman", districts: ["Merkez", "Besni", "Gölbaşı", "Kahta", "Çelikhan", "Gerger", "Samsat", "Sincik", "Tut"] },
  { label: "Afyonkarahisar", districts: ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ", "Çay", "Sultandağı", "İhsaniye", "Sinanpaşa", "Şuhut"] },
  { label: "Ağrı", districts: ["Merkez", "Doğubayazıt", "Patnos", "Diyadin", "Eleşkirt", "Hamur", "Taşlıçay", "Tutak"] },
  { label: "Amasya", districts: ["Merkez", "Merzifon", "Suluova", "Gümüşhacıköy", "Göynücek", "Hamamözü", "Taşova"] },
  { label: "Ankara", districts: ["Çankaya", "Keçiören", "Mamak", "Etimesgut", "Sincan", "Yenimahalle", "Altındağ", "Pursaklar", "Gölbaşı", "Çubuk", "Polatlı", "Beypazarı", "Haymana", "Şereflikoçhisar", "Kızılcahamam", "Kahramankazan", "Akyurt", "Elmadağ", "Evren", "Ayaş", "Bala", "Güdül", "Kalecik", "Nallıhan"] },
  { label: "Antalya", districts: ["Muratpaşa", "Konyaaltı", "Kepez", "Aksu", "Döşemealtı", "Alanya", "Manavgat", "Serik", "Kumluca", "Kemer", "Kaş", "Finike", "Gazipaşa", "Demre", "Elmalı", "Korkuteli", "Akseki", "Gündoğmuş", "İbradı"] },
  { label: "Artvin", districts: ["Merkez", "Arhavi", "Borçka", "Hopa", "Şavşat", "Yusufeli", "Ardanuç", "Murgul"] },
  { label: "Aydın", districts: ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "İncirliova", "Germencik", "Çine", "Bozdoğan", "Buharkent", "Karacasu", "Karpuzlu", "Koçarlı", "Köşk", "Sultanhisar", "Yenipazar", "Kuyucak"] },
  { label: "Balıkesir", districts: ["Altıeylül", "Karesi", "Bandırma", "Edremit", "Gönen", "Burhaniye", "Ayvalık", "Bigadiç", "Susurluk", "Erdek", "Havran", "İvrindi", "Dursunbey", "Savaştepe", "Sındırgı", "Manyas", "Marmara", "Balya", "Kepsut"] },
  { label: "Bilecik", districts: ["Merkez", "Bozüyük", "Söğüt", "Gölpazarı", "Osmaneli", "Pazaryeri", "İnhisar", "Yenipazar"] },
  { label: "Bingöl", districts: ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yayladere", "Yedisu"] },
  { label: "Bitlis", districts: ["Merkez", "Tatvan", "Ahlat", "Adilcevaz", "Güroymak", "Hizan", "Mutki"] },
  { label: "Bolu", districts: ["Merkez", "Gerede", "Mudurnu", "Göynük", "Mengen", "Dörtdivan", "Kıbrıscık", "Seben", "Yeniçağa"] },
  { label: "Burdur", districts: ["Merkez", "Bucak", "Gölhisar", "Tefenni", "Yeşilova", "Ağlasun", "Altınyayla", "Çavdır", "Çeltikçi", "Karamanlı", "Kemer"] },
  { label: "Bursa", districts: ["Osmangazi", "Nilüfer", "Yıldırım", "Gürsu", "Kestel", "Gemlik", "Mudanya", "İnegöl", "Orhangazi", "Mustafakemalpaşa", "Karacabey", "İznik", "Yenişehir", "Orhaneli", "Keles", "Büyükorhan", "Harmancık"] },
  { label: "Çanakkale", districts: ["Merkez", "Biga", "Çan", "Gelibolu", "Ayvacık", "Bayramiç", "Ezine", "Lapseki", "Yenice", "Bozcaada", "Gökçeada"] },
  { label: "Çankırı", districts: ["Merkez", "Çerkeş", "Ilgaz", "Kurşunlu", "Şabanözü", "Yapraklı", "Atkaracalar", "Bayramören", "Eldivan", "Kızılırmak", "Korgun", "Orta"] },
  { label: "Çorum", districts: ["Merkez", "Alaca", "Sungurlu", "Osmancık", "İskilip", "Bayat", "Kargı", "Laçin", "Mecitözü", "Oğuzlar", "Ortaköy", "Uğurludağ", "Boğazkale", "Dodurga"] },
  { label: "Denizli", districts: ["Merkezefendi", "Pamukkale", "Çivril", "Acıpayam", "Tavas", "Buldan", "Çal", "Sarayköy", "Honaz", "Kale", "Serinhisar", "Güney", "Baklan", "Beyağaç", "Babadağ", "Bekilli", "Bozkurt", "Çameli", "Çardak"] },
  { label: "Diyarbakır", districts: ["Bağlar", "Kayapınar", "Sur", "Yenişehir", "Bismil", "Ergani", "Çermik", "Silvan", "Dicle", "Çınar", "Çüngüş", "Eğil", "Hani", "Hazro", "Kocaköy", "Kulp", "Lice"] },
  { label: "Edirne", districts: ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Enez", "Lalapaşa", "Meriç", "Süloğlu"] },
  { label: "Elazığ", districts: ["Merkez", "Kovancılar", "Karakoçan", "Baskil", "Sivrice", "Maden", "Palu", "Arıcak", "Alacakaya", "Ağın", "Keban"] },
  { label: "Erzincan", districts: ["Merkez", "Tercan", "Üzümlü", "Çayırlı", "Refahiye", "İliç", "Kemah", "Kemaliye", "Otlukbeli"] },
  { label: "Erzurum", districts: ["Yakutiye", "Palandöken", "Aziziye", "Oltu", "Horasan", "Pasinler", "Hınıs", "Karayazı", "Aşkale", "İspir", "Narman", "Tortum", "Tekman", "Karaçoban", "Köprüköy", "Olur", "Çat", "Pazaryolu", "Şenkaya", "Uzundere"] },
  { label: "Eskişehir", districts: ["Odunpazarı", "Tepebaşı", "Çifteler", "Sivrihisar", "Mahmudiye", "Alpu", "Beylikova", "Günyüzü", "Han", "İnönü", "Mihalgazi", "Mihalıççık", "Sarıcakaya", "Seyitgazi"] },
  { label: "Gaziantep", districts: ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Oğuzeli", "Araban", "Karkamış", "Yavuzeli"] },
  { label: "Giresun", districts: ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Keşap", "Dereli", "Şebinkarahisar", "Alucra", "Güce", "Piraziz", "Yağlıdere", "Çamoluk", "Çanakçı", "Doğankent"] },
  { label: "Gümüşhane", districts: ["Merkez", "Kelkit", "Şiran", "Torul", "Köse", "Kürtün"] },
  { label: "Hakkari", districts: ["Merkez", "Yüksekova", "Şemdinli", "Çukurca"] },
  { label: "Hatay", districts: ["Antakya", "İskenderun", "Defne", "Arsuz", "Payas", "Dörtyol", "Kırıkhan", "Reyhanlı", "Samandağ", "Altınözü", "Belen", "Erzin", "Hassa", "Kumlu", "Yayladağı"] },
  { label: "Isparta", districts: ["Merkez", "Yalvaç", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Senirkent", "Uluborlu", "Keçiborlu", "Atabey", "Gönen", "Sütçüler", "Aksu", "Yenişarbademli"] },
  { label: "Mersin", districts: ["Akdeniz", "Mezitli", "Toroslar", "Yenişehir", "Tarsus", "Erdemli", "Silifke", "Anamur", "Mut", "Gülnar", "Aydıncık", "Bozyazı", "Çamlıyayla"] },
  { label: "İstanbul", districts: ["Kadıköy", "Beşiktaş", "Şişli", "Beyoğlu", "Fatih", "Bakırköy", "Üsküdar", "Ataşehir", "Maltepe", "Kartal", "Pendik", "Tuzla", "Sarıyer", "Beykoz", "Sultanbeyli", "Ümraniye", "Sancaktepe", "Çekmeköy", "Başakşehir", "Küçükçekmece", "Bahçelievler", "Bağcılar", "Esenler", "Güngören", "Bayrampaşa", "Eyüpsultan", "Gaziosmanpaşa", "Kağıthane", "Zeytinburnu", "Avcılar", "Esenyurt", "Beylikdüzü", "Büyükçekmece", "Arnavutköy", "Çatalca", "Silivri", "Sultanahmet", "Adalar", "Şile"] },
  { label: "İzmir", districts: ["Konak", "Bornova", "Karşıyaka", "Buca", "Bayraklı", "Çiğli", "Karabağlar", "Gaziemir", "Balçova", "Narlıdere", "Güzelbahçe", "Menemen", "Torbalı", "Ödemiş", "Bergama", "Tire", "Aliağa", "Urla", "Çeşme", "Dikili", "Foça", "Kemalpaşa", "Kiraz", "Menderes", "Seferihisar", "Selçuk", "Beydağ", "Bayındır", "Karaburun", "Kınık"] },
  { label: "Kars", districts: ["Merkez", "Sarıkamış", "Kağızman", "Digor", "Akyaka", "Arpaçay", "Selim", "Susuz"] },
  { label: "Kastamonu", districts: ["Merkez", "Tosya", "Taşköprü", "İnebolu", "Araç", "Cide", "Daday", "Devrekani", "Çatalzeytin", "Küre", "Abana", "Azdavay", "Bozkurt", "Doğanyurt", "Hanönü", "İhsangazi", "Pınarbaşı", "Seydiler", "Şenpazar"] },
  { label: "Kayseri", districts: ["Melikgazi", "Kocasinan", "Talas", "Hacılar", "İncesu", "Develi", "Bünyan", "Yahyalı", "Pınarbaşı", "Sarıoğlan", "Sarız", "Tomarza", "Yeşilhisar", "Akkışla", "Felahiye", "Özvatan"] },
  { label: "Kırklareli", districts: ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Kofçaz", "Pehlivanköy"] },
  { label: "Kırşehir", districts: ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Akçakent", "Boztepe"] },
  { label: "Kocaeli", districts: ["İzmit", "Gebze", "Darıca", "Çayırova", "Dilovası", "Gölcük", "Kandıra", "Karamürsel", "Kartepe", "Körfez", "Derince", "Başiskele"] },
  { label: "Konya", districts: ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Çumra", "Ilgın", "Kulu", "Cihanbeyli", "Seydişehir", "Karapınar", "Sarayönü", "Bozkır", "Hadim", "Taşkent", "Doğanhisar", "Hüyük", "Kadınhanı", "Altınekin", "Derebucak", "Emirgazi", "Güneysınır", "Halkapınar", "Tuzlukçu", "Yalıhüyük", "Ahırlı", "Çeltik", "Derbent"] },
  { label: "Kütahya", districts: ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Domaniç", "Altıntaş", "Aslanapa", "Çavdarhisar", "Dumlupınar", "Hisarcık", "Pazarlar", "Şaphane"] },
  { label: "Malatya", districts: ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Akçadağ", "Darende", "Hekimhan", "Arapgir", "Arguvan", "Kale", "Kuluncak", "Pütürge", "Yazıhan", "Doğanyol"] },
  { label: "Manisa", districts: ["Şehzadeler", "Yunusemre", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Saruhanlı", "Kula", "Demirci", "Gördes", "Köprübaşı", "Kırkağaç", "Sarıgöl", "Selendi", "Ahmetli", "Gölmarmara"] },
  { label: "Kahramanmaraş", districts: ["Dulkadiroğlu", "Onikişubat", "Elbistan", "Afşin", "Göksun", "Türkoğlu", "Pazarcık", "Andırın", "Çağlayancerit", "Ekinözü", "Nurhak"] },
  { label: "Mardin", districts: ["Artuklu", "Kızıltepe", "Midyat", "Nusaybin", "Derik", "Mazıdağı", "Dargeçit", "Ömerli", "Savur", "Yeşilli"] },
  { label: "Muğla", districts: ["Menteşe", "Bodrum", "Fethiye", "Marmaris", "Milas", "Dalaman", "Ortaca", "Datça", "Köyceğiz", "Ula", "Yatağan", "Kavaklıdere", "Seydikemer"] },
  { label: "Muş", districts: ["Merkez", "Malazgirt", "Bulanık", "Varto", "Hasköy", "Korkut"] },
  { label: "Nevşehir", districts: ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Derinkuyu", "Kozaklı", "Acıgöl", "Hacıbektaş"] },
  { label: "Niğde", districts: ["Merkez", "Bor", "Çamardı", "Ulukışla", "Altunhisar", "Çiftlik"] },
  { label: "Ordu", districts: ["Altınordu", "Ünye", "Fatsa", "Perşembe", "Korgan", "Kumru", "Mesudiye", "Gölköy", "Aybastı", "Akkuş", "Çamaş", "Çatalpınar", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Ulubey"] },
  { label: "Rize", districts: ["Merkez", "Çamlıhemşin", "Ardeşen", "Pazar", "Fındıklı", "Çayeli", "İkizdere", "Derepazarı", "Güneysu", "Hemşin", "İyidere", "Kalkandere"] },
  { label: "Sakarya", districts: ["Adapazarı", "Serdivan", "Erenler", "Arifiye", "Hendek", "Akyazı", "Geyve", "Sapanca", "Karasu", "Kaynarca", "Kocaali", "Pamukova", "Söğütlü", "Taraklı", "Ferizli", "Karapürçek"] },
  { label: "Samsun", districts: ["Atakum", "İlkadım", "Canik", "Tekkeköy", "Bafra", "Çarşamba", "Terme", "Vezirköprü", "Havza", "Kavak", "Ladik", "Salıpazarı", "19 Mayıs", "Alaçam", "Ayvacık", "Asarcık", "Yakakent"] },
  { label: "Siirt", districts: ["Merkez", "Kurtalan", "Baykan", "Eruh", "Pervari", "Şirvan", "Tillo"] },
  { label: "Sinop", districts: ["Merkez", "Boyabat", "Gerze", "Ayancık", "Türkeli", "Durağan", "Dikmen", "Erfelek", "Saraydüzü"] },
  { label: "Sivas", districts: ["Merkez", "Şarkışla", "Suşehri", "Zara", "Gemerek", "Kangal", "Yıldızeli", "Divriği", "Gürün", "Hafik", "İmranlı", "Koyulhisar", "Ulaş", "Akıncılar", "Altınyayla", "Doğanşar", "Gölova"] },
  { label: "Tekirdağ", districts: ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Kapaklı", "Ergene", "Hayrabolu", "Malkara", "Muratlı", "Saray", "Şarköy", "Marmaraereğlisi"] },
  { label: "Tokat", districts: ["Merkez", "Erbaa", "Turhal", "Niksar", "Zile", "Reşadiye", "Almus", "Artova", "Başçiftlik", "Pazar", "Sulusaray", "Yeşilyurt"] },
  { label: "Trabzon", districts: ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Arsin", "Sürmene", "Çarşıbaşı", "Beşikdüzü", "Vakfıkebir", "Maçka", "Tonya", "Çaykara", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Şalpazarı"] },
  { label: "Tunceli", districts: ["Merkez", "Pertek", "Çemişgezek", "Hozat", "Mazgirt", "Nazımiye", "Ovacık", "Pülümür"] },
  { label: "Şanlıurfa", districts: ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek", "Viranşehir", "Suruç", "Birecik", "Akçakale", "Ceylanpınar", "Bozova", "Hilvan", "Harran", "Halfeti"] },
  { label: "Uşak", districts: ["Merkez", "Eşme", "Banaz", "Sivaslı", "Karahallı", "Ulubey"] },
  { label: "Van", districts: ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Özalp", "Başkale", "Çaldıran", "Gevaş", "Gürpınar", "Muradiye", "Saray", "Çatak", "Bahçesaray"] },
  { label: "Yozgat", districts: ["Merkez", "Sorgun", "Yerköy", "Boğazlıyan", "Akdağmadeni", "Sarıkaya", "Çekerek", "Şefaatli", "Aydıncık", "Çandır", "Çayıralan", "Kadışehri", "Saraykent", "Yenifakılı"] },
  { label: "Zonguldak", districts: ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Alaplı", "Gökçebey", "Kilimli", "Kozlu"] },
  { label: "Aksaray", districts: ["Merkez", "Ortaköy", "Gülağaç", "Güzelyurt", "Ağaçören", "Eskil", "Sarıyahşi"] },
  { label: "Bayburt", districts: ["Merkez", "Aydıntepe", "Demirözü"] },
  { label: "Karaman", districts: ["Merkez", "Ermenek", "Sarıveliler", "Ayrancı", "Başyayla", "Kazımkarabekir"] },
  { label: "Kırıkkale", districts: ["Merkez", "Keskin", "Delice", "Yahşihan", "Sulakyurt", "Balışeyh", "Bahşili", "Çelebi", "Karakeçili"] },
  { label: "Batman", districts: ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş", "Hasankeyf"] },
  { label: "Şırnak", districts: ["Merkez", "Cizre", "Silopi", "İdil", "Uludere", "Beytüşşebap", "Güçlükonak"] },
  { label: "Bartın", districts: ["Merkez", "Amasra", "Kurucaşile", "Ulus"] },
  { label: "Ardahan", districts: ["Merkez", "Göle", "Çıldır", "Hanak", "Posof", "Damal"] },
  { label: "Iğdır", districts: ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"] },
  { label: "Yalova", districts: ["Merkez", "Çınarcık", "Altınova", "Armutlu", "Çiftlikköy", "Termal"] },
  { label: "Karabük", districts: ["Merkez", "Safranbolu", "Eskipazar", "Yenice", "Eflani", "Ovacık"] },
  { label: "Kilis", districts: ["Merkez", "Elbeyli", "Musabeyli", "Polateli"] },
  { label: "Osmaniye", districts: ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Hasanbeyli", "Sumbas", "Toprakkale"] },
  { label: "Düzce", districts: ["Merkez", "Akçakoca", "Cumayeri", "Çilimli", "Gölyaka", "Gümüşova", "Kaynaşlı", "Yığılca"] },
];

export const CITY_NAMES = CITIES.map((c) => c.label);

export function getDistricts(city: string): string[] {
  return CITIES.find((c) => c.label === city)?.districts ?? [];
}
